---
abstract: 'A minimalist HTTP user agent cookie jar'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::Deep: '0'
  Test::More: '0.96'
  Test::Requires: '0'
  Time::Local: '1.1901'
  Time::Mock: '0'
  URI: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-CookieJar
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  HTTP::CookieJar:
    file: lib/HTTP/CookieJar.pm
    version: '0.006'
  HTTP::CookieJar::LWP:
    file: lib/HTTP/CookieJar/LWP.pm
    version: '0.006'
recommends:
  Mozilla::PublicSuffix: '0'
requires:
  Carp: '0'
  HTTP::Date: '0'
  Time::Local: '1.1901'
  parent: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/HTTP-CookieJar/issues
  homepage: https://github.com/dagolden/HTTP-CookieJar
  repository: https://github.com/dagolden/HTTP-CookieJar.git
version: '0.006'
x_authority: cpan:DAGOLDEN
